server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  #MySQL驱动包
    url: jdbc:mysql://127.0.0.1:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

eureka:
  instance:
    hostname: localhost # 服务段实例名称
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
     #eureka服务端收到最后一次心跳后等待时间上限，超时将服务剔除
     #lease-expiration-duration-in-seconds: 5
     #eureka客户端向服务端发送心跳间隔时间，单位为秒，默认30
     #lease-renewal-interval-in-seconds:
  client:
    #表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心，职责就是维护服务实例，并不需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities  #所有entity别名类所在包

  #showSql
  logging:
    level:
      com:
        example:
          mapper: debug

