server:
  port: 3344

spring:
  application:
    name: cloud-config-server #注册进eureka服务名
  cloud:
    config:
      server:
        git:
          uri:      #github上面仓库的名字
          search-paths:
            - springcloud-config
      #读取的分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest


#暴露监控端点,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

